[project]
name = "mcp-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.55.0",
    "arxiv>=2.2.0",
    "mcp>=1.10.1",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.1",
]
